---
title: "Clustering spatial data"
date: "`r format(Sys.time(), '%d %m %Y')`"
format:
  html:
    embed-resources: true
    code-fold: show
params:
  fig.path: "./Figures/03_filt/"
editor_options: 
  chunk_output_type: console
---

```{r background-job, eval=FALSE, include=FALSE}
source("../bin/render_with_jobs.R")

# quarto
# render_html_with_job(out_dir = lab_dir)
# fs::file_move(path = file, new_path = paste0(lab_dir, file))

# currently using quarto for github and kniter for html due to source code option 
render_git_with_job(fig_path = "./Figures/03/")
# Change the figure path from ./Figures/03/ to ../Figures/03/:
system2(command = "sed", stdout = TRUE,
        args = c("-i", "''","-e", 's/src=\\"\\./src=\\"\\.\\./g',
                 paste0("./md_files/", basename("./03_clustering_st_data.md"))))

# kniter
knit_html_with_job(out_dir = "../lab_book/03_cluster_st_data", fig_path = "./Figures/03/")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    fig.width   = 6.6929133858,
    fig.path    = params$fig.path,
    dev         = c("png"),
    dpi         = 300,
    fig.align   = "center",
    message     = FALSE,
    warning     = FALSE,
    fig.process = function(filename){
      new_filename <- stringr::str_remove(string = filename, 
                                        pattern = "-1")
      fs::file_move(path = filename, new_path = new_filename)
      ifelse(fs::file_exists(new_filename), new_filename, filename)}) # fix this so that it always move the file into figure folder?
#  setwd("~/work/Brolidens_work/Projects/Spatial_Microbiota/src")
```

### Load data and libraries
```{r Load-Library-and-data}
##################
# LOAD LIBRARIES #
##################
library(tidyverse)
library(Seurat)
library(tidyseurat)
library(cowplot)
library(patchwork)

source("../bin/spatial_visualization.R")
source("../bin/plotting_functions.R")

#########
# PATHS #
#########
input_dir <- "../results/02_integrate_st_data/"
result_dir <- "../results/03_clustering_st_data/"
if( isFALSE(dir.exists(result_dir)) ) { dir.create(result_dir,recursive = TRUE) }

#############
# LODA DATA #
#############
DATA <- readRDS(paste0(input_dir,"seuratObj_integrated.RDS")) 

#################
# COLOUR PALLET #
#################
clus_0.7 <- c("#CD9600","#00A9FF","#e0e067","#7CAE00","#377EB8","#E41A1C","#FF7F00","#C77CFF",
              "#984EA3","#FF61CC","#FF9DA7","#999999","#A65628","#B07AA1", "#FF9DA7")
clus_0.9 <- c("#CD9600","#00A9FF","#e0e067","#7CAE00","#377EB8","#00BFC4","#FF7F00","#C77CFF",
            "#FF61CC","#E41A1C","#984EA3","#FFFF33","#FF9DA7","#999999","#A65628")
```

## Clustering
```{r Clustering-resolution}
##################################
# EVALUATE CLUSTERING RESOLUTION #
##################################
DATA <- FindNeighbors(DATA, reduction = "harmony", dims = 1:30, k.param = 15, prune.SNN = 1/15) 

# Clustering with louvain (algorithm 1) or leiden (algorithm 4)
for (res in c(0.1, 0.5, 0.7, 0.9, 1)) {
    DATA <- FindClusters(DATA, resolution = res, algorithm = 1)
}

# each time you run clustering, the data is stored in meta data columns:
# seurat_clusters - lastest results only RNA_snn_res.XX - for each different
# resolution you test.
```

### UMAP of cluster resolutions
```{r 03a_plot_resolution, fig.asp=5/10}
# dev.new(width=6.6929133858, height=3.3, noRStudioGD = TRUE)
res <- c("RNA_snn_res.0.7", "RNA_snn_res.0.9")
p <- map2(res, list(clus_0.7, clus_0.9),
          ~plot_clusters.fun(DATA, cluster=.x, txt_size = 10, dot_size = 0.2,
                             color = .y, red = "umapharmony") + xlab("UMAP 1") + ylab("UMAP 2")) 
plot_grid(ncol = 2, 
          plotlist = p)

```

### Cluster resolutions on tissue
```{r, 03b_plot_resolutions_on_tissue, fig.height=42, fig.width=7.5, dev = c("png", "pdf")}
# dev.new(width=7.5, height=42, noRStudioGD = TRUE)
plots <- DATA %>%
  mutate(group = orig.ident) %>%
  nest(., data = -group) %>%
  mutate( "res_1" = pmap(., 
    ~plot_spatial.fun(..2, sampleid=..1, geneid="RNA_snn_res.0.7", 
                      point_size = 0.7, zoom="zoom", colors = clus_0.5))) %>%
  mutate( "res_2" = pmap(., 
    ~plot_spatial.fun(..2, sampleid=..1, geneid="RNA_snn_res.09", 
                      point_size = 0.7, zoom="zoom", colors = clus_0.7)))

legend_1 <- get_legend(plots$res_1[[2]] + theme(legend.position="right"))
legend_2 <- get_legend(plots$res_2[[1]] + theme(legend.position="right"))
legend <- plot_grid( legend_1, legend_2, ncol = 1)
combined <- wrap_plots(plotlist=c(plots$res_1, plots$res_2), nrow = 21, byrow = F) & theme(legend.position="none")
combined <- plot_grid( combined, legend, ncol = 2, rel_widths = c(1, .3)) 
combined
# ggsave(paste0("./", "test_SCT.pdf"), combined, width=7.5, height=42)
```

### Set cluster resolution
```{r set-resolution}
DATA <- DATA %>%
  rename(Clusters="RNA_snn_res.0.7") %>%
  rename(Clusters_0.7="RNA_snn_res.0.9") %>%
  SetIdent(., value = "Clusters") %>%
  select(-any_of(contains(c("RNA_snn_res","seurat_clusters"))))
```

```{r 03c_Final_cluster_resolution, fig.height=3.3, fig.width=3.3, dev=c("png","pdf")}
# dev.new(width=3.3, height=3.3, noRStudioGD = TRUE)
p[[1]] + ggtitle("")
```

### Plot final clusters on tissue section:
```{r 03c_clust_plot, fig.height=1.7*6, fig.width=2*4, dev = c("png", "pdf")}
# Horizontal (aspect = width/height)
# dev.new(width=12.5, height=12.5, noRStudioGD = TRUE)
############################
# PLOT FACET WRAP CLUSTERS #
############################
(p <- plot_st_meta.fun( DATA,
        feat =  "Clusters",
        zoom = "zoom",
        colors = clus_0.5,
        alpha = .9,
        ncol = 4,
        #annot_col = "#dbd9d9",
        annot_line = .1,
        img_alpha = 0,
        point_size = .6))
      
```

```{r, add-layer-annotation}
###################
# ADD ANNOTATION #
##################
ord1 <- c("Superficial", "Upper IM", "Lower IM", "Basal","1","4","0","3","2","9","10","11","12")
ord2 <- c("5", "6", "7", "8", "1","4","0","3","2","9","10","11","12")

epi_layers <- set_names(ord1, ord2)

DATA <- DATA %>%
mutate(layers = factor(epi_layers[as.character(.$Clusters)], levels = ord1), .after = "orig.ident")
```

### Spot distribution by clusters
```{r spot-distribution-by-clusters, results='hold'}
DATA_sub <- as_tibble(DATA) %>%
  mutate(gr = .$groups) %>%
  mutate(ID = .$orig.ident) %>%
  nest(., data=-c(gr, orig.ident)) %>%
  mutate(epi =  map(data, ~filter(.x, !(sp_annot == "SubMuc"))),
         subMuc =  map(data, ~filter(.x, sp_annot == "SubMuc"))) %>%
  mutate(across(c("epi", "subMuc"), ~map(., ~table(.x$Clusters)), .names = "{.col}_n_before")) %>%
  mutate(across(contains("_n_"), ~set_names(.x, paste0(.data[["gr"]],"_",.data[["orig.ident"]]))))
      
table(DATA$Clusters)
n_samples <- length(unique(DATA$orig.ident))

t <- list(DATA_sub$epi_n_before, DATA_sub$subMuc_n_before) %>%
  map(., ~ .x %>%
        bind_cols("Clus" = paste0("**",names(table(DATA$Clusters)),"**"), .) %>%
        rowwise() %>% 
        mutate("Clus " = Clus,
               L1_sum = sum(c_across(starts_with("L1_"))),
               L2_sum = sum(c_across(starts_with("L2_"))),
               L3_sum = sum(c_across(starts_with("L3_"))),
               L4_sum = sum(c_across(starts_with("L4_")))) %>%
        select("Clus ", sort(colnames(.)[2:n_samples]), everything()) %>%
        arrange(match(Clus, paste0("**", ord2, "**")))
  )

knitr::kable(t[[1]][,1:(n_samples+1)], caption = "Distribution of epithelial spots per cluster per subject")
knitr::kable(t[[1]][,c(1,(n_samples+3):ncol(t[[1]]))], caption = "Distribution of epithelial spots per group")

knitr::kable(t[[2]][,1:n_samples], caption = "Distribution of submucosal spots per cluster per subject")
knitr::kable(t[[2]][,c(1,(n_samples+3):ncol(t[[1]]))], caption = "Distribution of submucosal spots per group")

```


The log2 count can work as a proxy for cell density. Here we see the distribution of counts per cluster
```{r 03d_log2count_per_cluster}
clus_col <- c("#E41A1C","#FF7F00","#C77CFF","#984EA3","#00A9FF","#377EB8",
               "#CD9600","#7CAE00","#e0e067","#FF61CC","#FF9DA7","#999999","#A65628") #,"#B07AA1",
clus_lvl <- c("5", "6", "7", "8", "1","4","0","3","2","9","10","11","12")

DATA %>%
  mutate("Count (log2)" = log2(.$nCount_RNA)) %>%
  mutate(Clusters = factor(.$Clusters, levels = clus_lvl)) %>%
  
  ggplot(., aes(x=Clusters, y=`Count (log2)`, fill=Clusters, color=Clusters)) + 
  geom_violin() + theme_light() +
  scale_fill_manual(values = clus_col, aesthetics = c("fill","colour"))

```

## Save seurat object
```{r save-SeuratObject}
##################################
# SAVE INTERMEDIATE SEURAT OJECT #
##################################
saveRDS(DATA, paste0(result_dir,"seuratObj_clustered.RDS"))
# DATA <- readRDS(paste0(result_dir,"seuratObj_clustered.RDS"))
```


### Session info
```{r}
sessionInfo()
```
