---
title: "Supplemental Figure 1"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    embed-resources: true
    code-fold: show
params:
  fig.path: "`r paste0(params$fig.path)`" #./Figures/
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width     = 6.6929133858,
  fig.path      = params$fig.path,#"../Figures/",
  fig.align     = "center",
  message       = FALSE,
  warning       = FALSE,
  dev           = c("png"),
  dpi           = 300,
  fig.process = function(filename){
    new_filename <- stringr::str_remove(string = filename,
                                        pattern = "-1")
    fs::file_move(path = filename, new_path = new_filename)
    ifelse(fs::file_exists(new_filename), new_filename, filename)
  }
  )
# setwd("~/work/Brolidens_work/Projects/Spatial_Microbiota/src/Manuscript")
```

```{r background_job, eval=FALSE, include=FALSE}
source("../../bin/render_with_jobs.R")

# quarto
# render_html_with_job(out_dir = lab_dir)
# fs::file_move(path = file, new_path = paste0(lab_dir, file))

# currently using quarto for github and kniter for html due to source code option 
render_git_with_job(fig_path = "./Figures/S1/")
system2(command = "sed", stdout = TRUE,
        args = c("-i", "''","-e", 's/src=\\"\\./src=\\"\\.\\./g',
                 paste0("./md_files/", basename("./Figure_S1.md"))))

# kniter
knit_html_with_job(out_dir = "../lab_book/Figures_S1", fig_path = "./Figures/S1/")
```

### Load data and libraries
```{r Load_data}
##################
# LOAD LIBRARIES #
##################
library(tidyverse)
library(Seurat)
library(SeuratObject)
library(tidyseurat)
library(cowplot)
library(ggrepel)
library(png)
library(grid)

source("../../bin/spatial_visualization.R")
source("../../bin/plotting_functions.R")

#########
# PATHS #
#########
input_dir <- "../../results/03_clustering_st_data/"
result_dir <- "../../results/09_figures/"
if( isFALSE(dir.exists(result_dir)) ) { dir.create(result_dir,recursive = TRUE) }
epi_clus <- "^5$|^6$|^7|^9" # non-filt

#############
# LOAD DATA #
#############
DATA <- readRDS(paste0(input_dir,"seuratObj_clustered.RDS"))

#################
# COLOUR PALLET #
#################
sample_id <- c("P020", "P045", "P050", "P057",
               "P008", "P031", "P080", "P044", "P026", "P105", 
               "P001", "P004", "P014", "P018", "P087", "P118",
               "P021", "P024", "P067", "P081", "P117" )
friendly_cols <- c("#4E79A7", "#F28E2B", "#E15759", "#76B7B2", "#59A14F", "#EDC948", "#9C755F", 
                   "#B07AA1", "#FF9DA7", "#E78AC3", "#7FC97F", "#BEAED4", "#BAB0AC", "#FDC086",
                   "#FFFF99", "#386CB0", "#F0027F", "#BF5B17", "#666666", "#66C2A5", "#FC8D62", "#8DA0CB")
```

```{r QC-plots, fig.width = 7, fig.height = 3.3}
################################
# VIOLIN PLOT AFTER FILTERING #
################################
DAT <- DATA %>% mutate(orig.ident = factor(.$orig.ident, levels = sample_id))

feature <-  c("nCount_RNA", "nFeature_RNA")
A <-  map(feature, ~violin.fun(DAT, feature=.x, 
                               fill="orig.ident", 
                               col_pal=friendly_cols, 
                               n=1, txt_size=12, dot_size=.4))

```

```{r Figure-S1, fig.width=9, fig.height=9, dpi=1000}
#############################
# COMBINE ALL FIGURE PANELS #
#############################
# dev.new(width=8, height=9, noRStudioGD = TRUE)
Figure_S1 <- plot_grid(plotlist=A, nrow = 2, labels = c('A', 'B'))
# ggsave("./Figures/S1/FigureS1.pdf", Figure_S1, width = 8, height = 9, bg = "white", dpi = 1000)

Figure_S1
```

